CONFIG_FILE_NAME = "config"
INI_CONFIG_TYPE = "ini"
TOML_CONFIG_TYPE = "toml"

SUPPORTED_CONFIG_TYPES = [
    INI_CONFIG_TYPE,
    TOML_CONFIG_TYPE
]

DOTENV_FILE_NAME = ".env"

DAILY_TIMEFRAME = "daily"
WEEKLY_TIMEFRAME = "weekly"
MONTHLY_TIMEFRAME = "monthly"

SUPPORTED_TIMEFRAMES = [
    DAILY_TIMEFRAME,
    WEEKLY_TIMEFRAME,
    MONTHLY_TIMEFRAME
]

# sensible data labels following .env format
API_KEY = "API_KEY"
API_SECRET = "API_SECRET"

# OBSIDIAN_VAULT_ROOT_DIR = "OBSIDIAN_VAULT_ROOT_PATH"
# OBSIDIAN_JOURNAL_DIR = "OBSIDIAN_JOURNAL_PATH"

# endpoint labels following .ini format

BASE_URL = "base_url"
TRANSACTION_LOG_ENDPOINT_LABEL = "transaction_log_endpoint"
EXECUTION_LIST_ENDPOINT_LABEL = "execution_list_endpoint"
ORDER_HISTORY_ENDPOINT_LABEL = "order_history_endpoint"
REALTIME_ORDER_ENDPOINT_LABEL = "realtime_order_endpoint"

# other

ENDPOINTS_TO_PROCESS = [
    TRANSACTION_LOG_ENDPOINT_LABEL,
    EXECUTION_LIST_ENDPOINT_LABEL,
    ORDER_HISTORY_ENDPOINT_LABEL
#    REALTIME_ORDER_ENDPOINT_LABEL
]

TRADES_DATASET = "trades"
TRANSACTIONS_DATASET = "transactions"
ORDER_HISTORY_DATASET = "order_history"

HTTP_VALID_RESPONSE_CODES = [200,]
API_VALID_INTERNAL_RESPONSE_CODES = [0,]

DEFAULT_DATE_FORMAT = "%d-%m-%Y %H:%M:%S"
VALID_INPUT_DATE_FORMATS = ["%Y-%m-%d", "%Y-%m"]
DAYS_PAGINATION_SIZE = 6

CONTAINER_MODE = "CONTAINER_MODE"

RISK_THRESHOLD = 0.01