# dataframe formatted columns
COL_NAME_SYMBOL = "Symbol"
COL_NAME_TYPE = "Type"
COL_NAME_ACTION = "Action"
COL_NAME_SIDE = "Side"
COL_NAME_FEE = "Fee"
COL_NAME_FEE_RATE = "Fee Rate"
COL_NAME_REM_SIZE = "Size"
COL_NAME_QUANTITY = "Quantity"
COL_NAME_STOP_LOSS = "Stop Loss"
COL_NAME_TAKE_PROFIT = "Take Profit"
COL_NAME_EXEC_PRICE = "Entry Price"
COL_NAME_EXEC_DATE = "Entry Date"
COL_NAME_CLOSED_SIZE = "Closed Size"
COL_NAME_GROSS_PROFIT = "Gross Profit"
COL_NAME_REALIZED_PROFIT = "Realized Profit"
COL_NAME_ACC_BALANCE = "Wallet Balance"
COL_NAME_ROI = "ROI"
COL_NAME_ROI_PERCENT = "ROI(%)"
COL_NAME_ATTACHMENTS = "Attachments"
COL_NAME_CONFLUENCE = "Confluence"
COL_NAME_REMARKS = "Other Remarks"

COL_NAME_SL_SET = "Preset SL"
COL_NAME_TP_SET = "Preset TP"
COL_NAME_SL_TRIGGERED = "Stopped At"
COL_NAME_STOPPED_OUT = "Stopped Out"
COL_NAME_EXIT_PRICE = "Exit Price (Avg.)"
COL_NAME_TAKE_PROFITS = "Take Profits"
COL_NAME_IS_CLOSED = "Closed"
COL_NAME_CLOSED_DATE = "Closed Date"
COL_NAME_TRADE_STATUS = "Status"
COL_NAME_RISK_TAKEN = "Risk"
COL_NAME_RISK_TAKEN_PERCENT = "Risk(%)"
COL_NAME_RISK_MANAGED = "Risk Managed"
COL_NAME_TRADE_DURATION = "Duration"
COL_NAME_TRADE_SESSION = "Session"


AGGREGATED_VIEW_USABLE_COLUMNS = [
    COL_NAME_SYMBOL,
    COL_NAME_SIDE,
    COL_NAME_IS_CLOSED,
    COL_NAME_RISK_MANAGED,
    COL_NAME_TRADE_STATUS,
    COL_NAME_TRADE_SESSION,
    COL_NAME_QUANTITY,
    COL_NAME_EXEC_PRICE,
    COL_NAME_EXEC_DATE,
    COL_NAME_EXIT_PRICE,
    COL_NAME_CLOSED_DATE,
    COL_NAME_SL_SET,
    COL_NAME_SL_TRIGGERED,
    COL_NAME_STOPPED_OUT,
    COL_NAME_TAKE_PROFITS,
    COL_NAME_RISK_TAKEN,
    #COL_NAME_RISK_TAKEN_PERCENT,
    # add total fees and fees(%)
    COL_NAME_GROSS_PROFIT,
    COL_NAME_REALIZED_PROFIT,
    COL_NAME_TRADE_DURATION
    # fee rate?
    # roi (%)
]
# other

NEW_ORDER_ACTION_LABEL = "New Order"
STOP_LOSS_ACTION_LABEL = "Stop Loss"
TAKE_PROFIT_ACTION_LABEL = "Take Profit"

WIN_RESULT_LABEL = "Win"
LOSS_RESULT_LABEL = "Loss"
BREAK_EVEN_RESULT_LABEL = "Break-even"
ONGOING_RESULT_LABEL = "Ongoing"